# Configuración del sitio
title: "Ciencia, Tecnología y Sociedad"
description: "Mis reflexiones en la búsqueda de la superación del determinismo"
author: "iapazmino"

# URL base (IMPORTANTE)
url: "https://iapazmino.github.io"
baseurl: ""  # vacío si el repo es iapazmino.github.io

# Configuración de Jekyll
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Plugins (opcional)
plugins:
  - jekyll-feed

# Tema
theme: minima
